name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t punisherblaine/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true punisherblaine/react-test npm test
 
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
 
      - name: Authenticate Google Cloud SDK
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
 
      - name: Build
        run: |-
          docker build -t punisherblaine/multi-client-10-14:latest -t punisherblaine/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t punisherblaine/multi-server-10-14:latest -t punisherblaine/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t punisherblaine/multi-worker-10-14:latest -t punisherblaine/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push punisherblaine/multi-client-10-14:latest
          docker push punisherblaine/multi-server-10-14:latest
          docker push punisherblaine/multi-worker-10-14:latest
 
          docker push punisherblaine/multi-client-k8s-gh:${{ env.SHA }}
          docker push punisherblaine/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push punisherblaine/multi-worker-k8s-gh:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s --validate=false
          kubectl set image deployments/server-deployment server=punisherblaine/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=punisherblaine/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=punisherblaine/multi-worker-k8s-gh:${{ env.SHA }}